[sdl]
fullscreen        = true
fulldouble        = false
fullresolution    = original
windowresolution  = original
output            = surface
videodriver       = dummy
autolock          = false
autolock_feedback = none
sensitivity       = 100
waitonerror       = false
priority          = highest,normal
mapperfile        = runtime/dosboxx.map
showmenu          = false

[dosbox]
title             = DOSBox-X
machine           = svga_s3
memsize           = 16

[render]
frameskip         = 0
aspect            = true
scaler            = none

[cpu]
core              = auto
cputype           = auto
cycles            = auto
cycleup           = 10
cycledown         = 20
apmbios           = true
isapnpbios        = false
integration device = false

[mixer]
rate              = 22050
blocksize         = 1024
prebuffer         = 20

[midi]
mpu401            = none

[sblaster]
sbtype            = sb16

[gus]
gus               = false

[speaker]
pcspeaker         = true
tandy             = auto
disney            = false

[joystick]
joysticktype      = none

[serial]
serial1           = disabled
serial2           = disabled
serial3           = disabled
serial4           = disabled

[ipx]
ipx               = false

[dos]
xms               = true
ems               = true
umb               = true

[autoexec]
@ECHO OFF
MOUNT C runtime/drive_c
MOUNT D runtime/shared
C:
CLS
TYPE README.TXT
