#!/bin/bash
# build_htop.sh — build a static ARMv7 htop with built-in terminal fallbacks

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/build"
SRC_DIR="$BUILD_DIR/src"

HTOP_VERSION="3.4.1"
HTOP_ARCHIVE="htop-$HTOP_VERSION.tar.xz"
HTOP_URL="https://github.com/htop-dev/htop/releases/download/$HTOP_VERSION/$HTOP_ARCHIVE"
HTOP_SRC_DIR="$BUILD_DIR/htop-$HTOP_VERSION"

NCURSES_VERSION="6.5"
NCURSES_ARCHIVE="ncurses-$NCURSES_VERSION.tar.gz"
NCURSES_URL="https://ftp.gnu.org/pub/gnu/ncurses/$NCURSES_ARCHIVE"
NCURSES_SRC_DIR="$BUILD_DIR/ncurses-$NCURSES_VERSION"

detect_cross_prefix() {
    local candidates=()

    if [ -n "${HTOP_CROSS_PREFIX:-}" ]; then
        candidates+=("$HTOP_CROSS_PREFIX")
    fi
    if [ -n "${CROSS_PREFIX:-}" ]; then
        candidates+=("$CROSS_PREFIX")
    fi
    candidates+=(
        arm-unknown-linux-musleabihf
        arm-linux-musleabihf
        arm-unknown-linux-gnueabihf
        arm-linux-gnueabihf
    )

    for prefix in "${candidates[@]}"; do
        if command -v "${prefix}-gcc" >/dev/null 2>&1; then
            printf '%s\n' "$prefix"
            return 0
        fi
    done

    printf '%s\n' "${HTOP_CROSS_PREFIX:-arm-unknown-linux-musleabihf}"
}

HOST_PREFIX="$(detect_cross_prefix)"
CC="$HOST_PREFIX-gcc"
AR="$HOST_PREFIX-ar"
RANLIB="$HOST_PREFIX-ranlib"
STRIP="$HOST_PREFIX-strip"
READELF="$HOST_PREFIX-readelf"

JOBS="${JOBS:-$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4)}"
ARCH_FLAGS="-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard"
OPT_FLAGS="-Os"
COMMON_CFLAGS="$ARCH_FLAGS $OPT_FLAGS"
PREFIX_DIR="$BUILD_DIR/prefix"
OUTPUT_BIN="$BUILD_DIR/htop"
STATIC_LINK=0

case "$HOST_PREFIX" in
    *musl*)
        STATIC_LINK=1
        ;;
esac

clean_build() {
    echo "Cleaning htop build artifacts..."
    rm -rf \
        "$PREFIX_DIR" \
        "$HTOP_SRC_DIR" \
        "$NCURSES_SRC_DIR" \
        "$OUTPUT_BIN"
    echo "Done."
}

if [ "${1:-}" = "clean" ]; then
    clean_build
    exit 0
fi

require_tool() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "ERROR: required tool '$1' not found in PATH"
        exit 1
    fi
}

download_if_missing() {
    url="$1"
    out="$2"
    if [ -f "$out" ]; then
        return 0
    fi

    if command -v curl >/dev/null 2>&1; then
        curl -fL --retry 3 -o "$out" "$url"
        return 0
    fi
    if command -v wget >/dev/null 2>&1; then
        wget -O "$out" "$url"
        return 0
    fi

    echo "ERROR: curl or wget is required to download third-party sources"
    exit 1
}

extract_if_missing() {
    archive="$1"
    out_dir="$2"
    if [ -d "$out_dir" ]; then
        return 0
    fi

    case "$archive" in
        *.tar.gz) tar -xzf "$archive" -C "$BUILD_DIR" ;;
        *.tar.xz) tar -xJf "$archive" -C "$BUILD_DIR" ;;
        *)
            echo "ERROR: unsupported archive format: $archive"
            exit 1
            ;;
    esac
}

patch_ncurses_fallbacks() {
    script="$NCURSES_SRC_DIR/ncurses/tinfo/MKfallback.sh"

    cat > "$script" <<'EOF'
#!/bin/sh
# Gemini patch: generate fallback terminals directly from the host terminfo DB.
# This avoids relying on target-side terminfo files and keeps htop self-contained.

terminfo_dir=$1
shift

terminfo_src=$1
shift

tic_path=$1
test -z "$tic_path" && tic_path=tic
shift

infocmp_path=$1
test -z "$infocmp_path" && infocmp_path=infocmp
shift

cat <<EOF2
/* This file was generated by $0 (Gemini patched) */

/*
 * DO NOT EDIT THIS FILE BY HAND!
 */

#include <curses.priv.h>

EOF2

if [ "$*" ]
then
	cat <<EOF2
#include <tic.h>

/* fallback entries for: $* */
EOF2
	for x in "$@"
	do
		echo "/* $x */"
		"$infocmp_path" -E "$x" | sed \
			-e 's/^static short /static int /' \
			-e 's/\<short\>/NCURSES_INT2/g'
	done

	cat <<EOF2
static const TERMTYPE2 fallbacks[$#] =
{
EOF2
	comma=""
	for x in "$@"
	do
		echo "$comma /* $x */"
		"$infocmp_path" -e "$x"
		comma=","
	done

	cat <<EOF2
};

EOF2
fi

cat <<EOF2
NCURSES_EXPORT(const TERMTYPE2 *)
_nc_fallback2 (const char *name GCC_UNUSED)
{
EOF2

if [ "$*" ]
then
	cat <<EOF2
    const TERMTYPE2	*tp;

    for (tp = fallbacks;
	 tp < fallbacks + sizeof(fallbacks)/sizeof(TERMTYPE2);
	 tp++) {
	if (_nc_name_match(tp->term_names, name, "|")) {
	    return(tp);
	}
    }
EOF2
else
	echo "	/* the fallback list is empty */"
fi

cat <<EOF2
    return((const TERMTYPE2 *)0);
}

#if NCURSES_EXT_NUMBERS
#undef _nc_fallback

NCURSES_EXPORT(const TERMTYPE *)
_nc_fallback (const char *name)
{
    const TERMTYPE2 *tp = _nc_fallback2(name);
    const TERMTYPE *result = 0;
    if (tp != 0) {
	static TERMTYPE temp;
	_nc_export_termtype2(&temp, tp);
	result = &temp;
    }
    return result;
}
#endif
EOF2
EOF

    chmod +x "$script"
}

require_tool "$CC"
require_tool "$AR"
require_tool "$RANLIB"
require_tool "$STRIP"
require_tool "$READELF"
require_tool make
require_tool python3
require_tool tar
require_tool infocmp

for term in xterm xterm-256color screen screen-256color linux vt100 ansi; do
    if ! infocmp "$term" >/dev/null 2>&1; then
        echo "ERROR: host terminfo entry '$term' is missing; cannot embed terminal fallbacks"
        exit 1
    fi
done

mkdir -p "$BUILD_DIR" "$SRC_DIR" "$PREFIX_DIR"

echo "[htop] Fetching sources..."
download_if_missing "$NCURSES_URL" "$SRC_DIR/$NCURSES_ARCHIVE"
download_if_missing "$HTOP_URL" "$SRC_DIR/$HTOP_ARCHIVE"
extract_if_missing "$SRC_DIR/$NCURSES_ARCHIVE" "$NCURSES_SRC_DIR"
extract_if_missing "$SRC_DIR/$HTOP_ARCHIVE" "$HTOP_SRC_DIR"

echo "[htop] Preparing ncurses fallback patch..."
patch_ncurses_fallbacks

echo "[htop] Configuring ncurses..."
(
    cd "$NCURSES_SRC_DIR"
    ./configure \
        --host="$HOST_PREFIX" \
        --prefix="$PREFIX_DIR" \
        --with-build-cc=cc \
        --without-ada \
        --without-cxx \
        --without-cxx-binding \
        --without-debug \
        --without-manpages \
        --without-shared \
        --with-normal \
        --without-tests \
        --enable-widec \
        --with-termlib \
        --with-fallbacks=xterm,xterm-256color,screen,screen-256color,linux,vt100,ansi \
        CC="$CC" \
        AR="$AR" \
        RANLIB="$RANLIB" \
        STRIP="$STRIP" \
        CFLAGS="$COMMON_CFLAGS"
)

echo "[htop] Building ncurses..."
make -C "$NCURSES_SRC_DIR" -j"$JOBS"
make -C "$NCURSES_SRC_DIR" install.libs install.includes

echo "[htop] Configuring htop..."
(
    cd "$HTOP_SRC_DIR"
    ./configure \
        --host="$HOST_PREFIX" \
        --prefix="$PREFIX_DIR" \
        --enable-static \
        --enable-unicode \
        --disable-capabilities \
        --disable-delayacct \
        --disable-sensors \
        --disable-openvz \
        --disable-vserver \
        --disable-unwind \
        --with-curses=ncursesw \
        CC="$CC" \
        AR="$AR" \
        RANLIB="$RANLIB" \
        STRIP="$STRIP" \
        CFLAGS="$COMMON_CFLAGS" \
        CPPFLAGS="-I$PREFIX_DIR/include" \
        LDFLAGS="-L$PREFIX_DIR/lib${STATIC_LINK:+ -static}" \
        CURSES_CFLAGS="-I$PREFIX_DIR/include" \
        CURSES_LIBS="-L$PREFIX_DIR/lib -lncursesw -ltinfow"
)

echo "[htop] Building htop..."
make -C "$HTOP_SRC_DIR" -j"$JOBS"

cp "$HTOP_SRC_DIR/htop" "$OUTPUT_BIN"
"$STRIP" "$OUTPUT_BIN"

if [ "$STATIC_LINK" -eq 1 ]; then
    echo "[htop] Verifying static binary..."
    if "$READELF" -d "$OUTPUT_BIN" 2>/dev/null | grep -q "Dynamic section"; then
        echo "ERROR: htop binary is not fully static"
        exit 1
    fi
else
    echo "[htop] Built dynamically linked binary with $HOST_PREFIX"
fi

echo ""
file "$OUTPUT_BIN"
echo ""
echo "htop binary exported to:"
echo "  $OUTPUT_BIN"
