[sdl]
fullscreen        = true
fulldouble        = false
fullresolution    = original
windowresolution  = original
output            = surface
videodriver       = dummy
autolock          = false
autolock_feedback = none
waitonerror       = false
priority          = highest,normal
mapperfile        = runtime/win31.map
showmenu          = false

[dosbox]
title             = Windows 3.1
machine           = svga_et4000
memsize           = 16

[render]
frameskip         = 0
aspect            = true
scaler            = none

[cpu]
core               = auto
cputype            = 486_slow
cycles             = auto
apmbios            = true
isapnpbios         = false
integration device = true

[keyboard]
aux               = true
auxdevice         = intellimouse

[mixer]
rate              = 22050
blocksize         = 1024
prebuffer         = 20

[midi]
mpu401            = none

[sblaster]
sbtype            = sb16

[gus]
gus               = false

[joystick]
joysticktype      = none

[ipx]
ipx               = false

[dos]
xms               = true
ems               = true
umb               = true

[autoexec]
@ECHO OFF
IMGMOUNT 2 images/system.img -t hdd -fs none
BOOT 2
